spring.application.name=tds_erickbarneche

spring.datasource.url=jdbc:mariadb://localhost:3306/tds_erickbarneche?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${MARIADB_SECRET:mariadb}

spring.jpa.hibernate.ddl-auto=update
# JPA-SQL (as propriedades abaixo instruem o Spring Boot a imprimir o SQL e formatá-lo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true